# -*- coding: utf-8 -*-
"""Guess the Number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NmsY_SC-HBBXXei46GpKGly5FOd_9Og7
"""

import random


# Generate a random four-digit number
def generate_random_number():
    return ''.join(random.sample('0123456789', 4))


# Function to compare the guessed numbers with the secret number
def compare_numbers(secret_number, guess):
    hint = ''

    # Compare each digit of the guess with the secret number
    for i in range(4):
        # Digit is correct and in the correct position
        if guess[i] == secret_number[i]:
            hint += 'O'
            # Digit is correct but in the wrong position
        elif guess[i] in secret_number:
            hint += 'X'
            # No matching digit at this position
        else:
            hint += 'F'

    return hint


# Main game function
def play_game():
    # Generate a secret number for the player to guess
    secret_number = generate_random_number()
    attempts = 0

    # Display the welcome message
    print("Welcome to the Guess the Number!")
    print("Type 'Exit' to quit the game.")

    # Game loop
    while True:
        guess = input("Please enter a four-digit number: ")

        # Check if the player wants to exit the game
        if guess == 'exit':
            print("You are GG！ The correct answer is:", secret_number)
            break

        # Validate the input
        if len(guess) != 4 or not guess.isdigit():
            print("Please enter a valid four-digit number.")
            continue

        # Increment the attempts counter
        attempts += 1
        # Get the hint for the current guess
        hint = compare_numbers(secret_number, guess)
        print("Hint:", hint)

        # Check if the player guessed correctly
        if hint == 'OOOO':
            print(f"Congratulations! You guessed it right in {attempts} attempts.")
            play_again = input("Do you want to play again? (Y/N): ")
            if play_again.lower() != 'Y':
                print("GG")
                break


# Run the game
play_game()